### ISSUE TITLE
Setup Storybook

### ISSUE THREAD

**Issue by randallmorey** [randallmorey/shopping-list-ui#6]
The style guide provides developer documentation of styles, UI components with live examples, and example code.

Establish Ember Storybook with a trivial example component to get us started.

**Comment by fernandogelin** [comment]
@randallmorey Should we use `ember-freestyle` instead? It seems like a simpler, less cumbersome solution for our use case.

**Comment by randallmorey** [comment]
Sounds great!  #thumbs-up #winning

**Comment by randallmorey** [comment]
Closing for now.  We can come back to this later.
