### ISSUE TITLE
Item category route and components

### ISSUE THREAD

**Issue by randallmorey** [randallmorey/shopping-list-ui#8]
- [x] Create item category route /items/:id/categories/:id
- [x] Create new item category route /items/:id/categories/new
- [x] Redirect /items/:id/categories back up to /items/:id, since this is a no-op route
- [x] Compose existing assets to create this view

![](https://user-images.githubusercontent.com/8390120/69773673-73c4d200-1161-11ea-8f80-6c26ddd6e97d.png)

**Comment by fernandogelin** [comment]
@randallmorey changes for this issue are in the `feature-category` branch. There's an issue where the confirmation modal is not being triggered when transitioning out of the categories route when changes are made but not saved. The tests for that are commented out for now.
